services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=chat
    networks:
      - chat-net

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=chat
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - chat-net

  redis:
    image: redis:7
    networks:
      - chat-net

networks:
  chat-net:
    driver: bridge

volumes:
  mysql-data:
